# 1. HTTP to HTTPS 
server {
    listen 80;
    server_name top10news.jhoja.tech;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name top10news.jhoja.tech;

    # SSL Certificates 
    ssl_certificate /etc/letsencrypt/live/top10news.jhoja.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/top10news.jhoja.tech/privkey.pem;

    # React files serve 
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API Route (Backend)
    location /api/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}