name: Deploy to AWS with Docker & ECR

on:
  push:
    branches:
      - main


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # 1. GitHub AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # 2. AWS ECR 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. Backend Image 
    - name: Build and Push Backend
      run: |
        cd backend
        docker build -t 894759051454.dkr.ecr.ap-south-1.amazonaws.com/news-backend:latest .
        docker push 894759051454.dkr.ecr.ap-south-1.amazonaws.com/news-backend:latest

    # 4. Frontend Image 
    - name: Build and Push Frontend
      run: |
        cd frontend
        docker build -t 894759051454.dkr.ecr.ap-south-1.amazonaws.com/news-frontend:latest .
        docker push 894759051454.dkr.ecr.ap-south-1.amazonaws.com/news-frontend:latest

    # 5. EC2 Server 
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 894759051454.dkr.ecr.ap-south-1.amazonaws.com
          
          mkdir -p /home/ec2-user/news-app
          cd /home/ec2-user/news-app
          
          cat << 'EOF' > docker-compose.yml
          version: '3.8'
          services:
            backend:
              image: 894759051454.dkr.ecr.ap-south-1.amazonaws.com/news-backend:latest
              ports:
                - "5000:5000"
              env_file: .env
              restart: always
            frontend:
              image: 894759051454.dkr.ecr.ap-south-1.amazonaws.com/news-frontend:latest
              ports:
                - "80:80"
              depends_on:
                - backend
                restart: always
          EOF
          
          docker-compose pull
          docker-compose down
          docker-compose up -d